# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5fc0a4a833cebabde7e223a80e6002f"
application_url = "https://s8wccg0o80kgo0oc8c0ows84.91.107.219.207.sslip.io"
embedded = true
name = "ds-post-purchase"
handle = "ds-post-purchase"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "https://s8wccg0o80kgo0oc8c0ows84.91.107.219.207.sslip.io"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://s8wccg0o80kgo0oc8c0ows84.91.107.219.207.sslip.io/auth/callback",
  "https://s8wccg0o80kgo0oc8c0ows84.91.107.219.207.sslip.io/auth/shopify/callback",
  "https://s8wccg0o80kgo0oc8c0ows84.91.107.219.207.sslip.io/api/auth/callback"
]


[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[pos]
embedded = false
