# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5fc0a4a833cebabde7e223a80e6002f"
application_url = "https://domains-edit-installed-undefined.trycloudflare.com"
embedded = true
name = "ds-post-purchase"
handle = "ds-post-purchase"

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://domains-edit-installed-undefined.trycloudflare.com/auth/callback",
  "https://domains-edit-installed-undefined.trycloudflare.com/auth/shopify/callback",
  "https://domains-edit-installed-undefined.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "digitalsprung-theme.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
